### PR TITLE
support csv table

### LINKED ISSUE #4: Deck.gl fails with more than 16 thumbnail viewers
When we use a long list of thumbnails, Deck.gl fails after 16 thumbnails on Chrome

```
deck: WebGL context is lost
onError @ deck.ts:262
_onContextLost @ deck.ts:795
onContextLost @ deck.ts:764
```

See:
https://github.com/visgl/deck.gl/issues/4229

Options are either:

- 1: to use a "virtual grid" and only create viewports in the visible part of the page.

 - 2: Or we manually render thumbnails from `zarr.js` chunks, as on ome-ngff-validator, and paint to canvas.

Option 2 doesn't give us zoomable thumbnails, but we could still create a full viewer when you click on a Thumbnail?

### PR DESCRIPTION
**Pull request by will-moore**
This PR has a bunch of changes to give a "minimal viable product" which allows users to provide a custom csv table and have control over the additional zarr data columns that are added...
Fixes #4 - Doesn't use `viv` or `Deck.gl` for thumbnails, but instead we simply load zarr data for the smallest pyramid level and render by hand. (follow-up could load larger levels if the lowest level is too small)

* [x] app deployed at https://ome.github.io/ome-zarr-catalog/

PR deployed at https://deploy-preview-2--deft-vacherin-6c652f.netlify.app/

By default, this uses the csv file at /public/zarr_samples.csv to generate a table using the data from that csv but also adding a Thumbnail column. The app uses the "URL" column from the table to load the Zarr data and create a Thumbnail.

See https://deploy-preview-2--deft-vacherin-6c652f.netlify.app/

You can use a different CSV file by adding a `?csv=url_to_file.csv`. I've added a couple of examples in this PR: e.g:

https://deploy-preview-2--deft-vacherin-6c652f.netlify.app/?csv=https://raw.githubusercontent.com/will-moore/ome-zarr-catalog/add_readme/public/csv_examples/idr_study.csv

Its also possible to specify what Zarr data columns you want to add to the table. By default the app only adds `Thumbnail` column, but others from this list are available: `Version,Axes,shape,chunks,Wells,Fields,Keywords,Thumbnail`

E.g. this adds Version, shape, chunks, Thumbnail:

https://deploy-preview-2--deft-vacherin-6c652f.netlify.app/?csv=https://raw.githubusercontent.com/will-moore/ome-zarr-catalog/add_readme/public/csv_examples/idr_study.csv&columns=Version,shape,chunks,Thumbnail

Using the PR at https://github.com/IDR/ome-ngff-samples/pull/20 to host the full list of IDR samples (replacing the jekyll site) and adding all possible columns, this gives something like the current IDR samples page:

https://deploy-preview-2--deft-vacherin-6c652f.netlify.app/?csv=https://raw.githubusercontent.com/will-moore/ome-ngff-samples/replace_page_with_csv/_data/zarr_samples.csv&columns=Version,Axes,shape,chunks,Wells,Fields,Keywords,Thumbnail

Features not supported: links to study, images etc in IDR. For that we really need markdown support in this app

### CODE REVIEW

**Comment by sbesson** [comment]
See https://github.com/IDR/ome-ngff-samples/pull/20#pullrequestreview-1301179182 for a review based on the existing IDR samples catalog.

**Comment by will-moore** [comment]
@sbesson That commit fixes Keywords for labels and also adds 'plate' keyword for plate data (not supported before but this feels useful):

Screenshot 2023-02-16 at 12 47 20

**Comment by joshmoore** [comment]
Page deployed https://ome.github.io/ome-zarr-catalog/ but it's currently blank. See https://github.com/ome/ome-zarr-catalog/tree/gh-pages for the contents.

**Comment by will-moore** [comment]
https://ome.github.io/ome-zarr-catalog/ is live now, but icons are failing - need to check that they're fixed by this PR...

**Comment by will-moore** [comment]
@joshmoore You OK to merge this now? I think that the viewer icons should be fixed by that last commit.

**Comment by will-moore** [comment]
Grrr - same issues again with https://ome.github.io/ome-zarr-catalog/ 
https://ome.github.io/zarr_samples.csv is 404.. I'll fix...

**Pull request merged**
